/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package spinal.sim.vpi;

public class JNISharedMemIfaceJNI {
  public final static native long new_VectorUint8__SWIG_0();
  public final static native long new_VectorUint8__SWIG_1(long jarg1, VectorUint8 jarg1_);
  public final static native long VectorUint8_capacity(long jarg1, VectorUint8 jarg1_);
  public final static native void VectorUint8_reserve(long jarg1, VectorUint8 jarg1_, long jarg2);
  public final static native boolean VectorUint8_isEmpty(long jarg1, VectorUint8 jarg1_);
  public final static native void VectorUint8_clear(long jarg1, VectorUint8 jarg1_);
  public final static native long new_VectorUint8__SWIG_2(int jarg1, short jarg2);
  public final static native int VectorUint8_doSize(long jarg1, VectorUint8 jarg1_);
  public final static native void VectorUint8_doAdd__SWIG_0(long jarg1, VectorUint8 jarg1_, short jarg2);
  public final static native void VectorUint8_doAdd__SWIG_1(long jarg1, VectorUint8 jarg1_, int jarg2, short jarg3);
  public final static native short VectorUint8_doRemove(long jarg1, VectorUint8 jarg1_, int jarg2);
  public final static native short VectorUint8_doGet(long jarg1, VectorUint8 jarg1_, int jarg2);
  public final static native short VectorUint8_doSet(long jarg1, VectorUint8 jarg1_, int jarg2, short jarg3);
  public final static native void VectorUint8_doRemoveRange(long jarg1, VectorUint8 jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorUint8(long jarg1);
  public final static native long new_SharedMemIface(String jarg1, long jarg2);
  public final static native void delete_SharedMemIface(long jarg1);
  public final static native String SharedMemIface_print_signals(long jarg1, SharedMemIface jarg1_);
  public final static native java.math.BigInteger SharedMemIface_get_signal_handle(long jarg1, SharedMemIface jarg1_, String jarg2);
  public final static native long SharedMemIface_read(long jarg1, SharedMemIface jarg1_, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger SharedMemIface_read_u64(long jarg1, SharedMemIface jarg1_, java.math.BigInteger jarg2);
  public final static native long SharedMemIface_read_u32(long jarg1, SharedMemIface jarg1_, java.math.BigInteger jarg2);
  public final static native void SharedMemIface_write(long jarg1, SharedMemIface jarg1_, java.math.BigInteger jarg2, long jarg3, VectorUint8 jarg3_);
  public final static native void SharedMemIface_write_u64(long jarg1, SharedMemIface jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void SharedMemIface_write_u32(long jarg1, SharedMemIface jarg1_, java.math.BigInteger jarg2, long jarg3);
  public final static native void SharedMemIface_sleep(long jarg1, SharedMemIface jarg1_, java.math.BigInteger jarg2);
  public final static native void SharedMemIface_eval(long jarg1, SharedMemIface jarg1_);
  public final static native boolean SharedMemIface_error_happened(long jarg1, SharedMemIface jarg1_);
  public final static native String SharedMemIface_error_string(long jarg1, SharedMemIface jarg1_);
  public final static native void SharedMemIface_close(long jarg1, SharedMemIface jarg1_);
}
