/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package spinal.sim.vpi;

public class SharedMemIface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SharedMemIface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SharedMemIface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNISharedMemIfaceJNI.delete_SharedMemIface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SharedMemIface(String shmem_name_, long shmem_size_) {
    this(JNISharedMemIfaceJNI.new_SharedMemIface(shmem_name_, shmem_size_), true);
  }

  public String print_signals() {
    return JNISharedMemIfaceJNI.SharedMemIface_print_signals(swigCPtr, this);
  }

  public java.math.BigInteger get_signal_handle(String handle_name) {
    return JNISharedMemIfaceJNI.SharedMemIface_get_signal_handle(swigCPtr, this, handle_name);
  }

  public VectorUint8 read(java.math.BigInteger handle) {
    return new VectorUint8(JNISharedMemIfaceJNI.SharedMemIface_read(swigCPtr, this, handle), true);
  }

  public java.math.BigInteger read_u64(java.math.BigInteger handle) {
    return JNISharedMemIfaceJNI.SharedMemIface_read_u64(swigCPtr, this, handle);
  }

  public long read_u32(java.math.BigInteger handle) {
    return JNISharedMemIfaceJNI.SharedMemIface_read_u32(swigCPtr, this, handle);
  }

  public void write(java.math.BigInteger handle, VectorUint8 data) {
    JNISharedMemIfaceJNI.SharedMemIface_write(swigCPtr, this, handle, VectorUint8.getCPtr(data), data);
  }

  public void write_u64(java.math.BigInteger handle, java.math.BigInteger data) {
    JNISharedMemIfaceJNI.SharedMemIface_write_u64(swigCPtr, this, handle, data);
  }

  public void write_u32(java.math.BigInteger handle, long data) {
    JNISharedMemIfaceJNI.SharedMemIface_write_u32(swigCPtr, this, handle, data);
  }

  public void sleep(java.math.BigInteger sleep_cycles) {
    JNISharedMemIfaceJNI.SharedMemIface_sleep(swigCPtr, this, sleep_cycles);
  }

  public void eval() {
    JNISharedMemIfaceJNI.SharedMemIface_eval(swigCPtr, this);
  }

  public boolean error_happened() {
    return JNISharedMemIfaceJNI.SharedMemIface_error_happened(swigCPtr, this);
  }

  public String error_string() {
    return JNISharedMemIfaceJNI.SharedMemIface_error_string(swigCPtr, this);
  }

  public void close() {
    JNISharedMemIfaceJNI.SharedMemIface_close(swigCPtr, this);
  }

}
