/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package spinal.sim.vpi;

public class VectorUint8 extends java.util.AbstractList<Short> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorUint8(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorUint8 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNISharedMemIfaceJNI.delete_VectorUint8(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorUint8(short[] initialElements) {
    this();
    reserve(initialElements.length);

    for (short element : initialElements) {
      add(element);
    }
  }

  public VectorUint8(Iterable<Short> initialElements) {
    this();
    for (short element : initialElements) {
      add(element);
    }
  }

  public Short get(int index) {
    return doGet(index);
  }

  public Short set(int index, Short e) {
    return doSet(index, e);
  }

  public boolean add(Short e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Short e) {
    modCount++;
    doAdd(index, e);
  }

  public Short remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorUint8() {
    this(JNISharedMemIfaceJNI.new_VectorUint8__SWIG_0(), true);
  }

  public VectorUint8(VectorUint8 other) {
    this(JNISharedMemIfaceJNI.new_VectorUint8__SWIG_1(VectorUint8.getCPtr(other), other), true);
  }

  public long capacity() {
    return JNISharedMemIfaceJNI.VectorUint8_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    JNISharedMemIfaceJNI.VectorUint8_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return JNISharedMemIfaceJNI.VectorUint8_isEmpty(swigCPtr, this);
  }

  public void clear() {
    JNISharedMemIfaceJNI.VectorUint8_clear(swigCPtr, this);
  }

  public VectorUint8(int count, short value) {
    this(JNISharedMemIfaceJNI.new_VectorUint8__SWIG_2(count, value), true);
  }

  private int doSize() {
    return JNISharedMemIfaceJNI.VectorUint8_doSize(swigCPtr, this);
  }

  private void doAdd(short x) {
    JNISharedMemIfaceJNI.VectorUint8_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, short x) {
    JNISharedMemIfaceJNI.VectorUint8_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private short doRemove(int index) {
    return JNISharedMemIfaceJNI.VectorUint8_doRemove(swigCPtr, this, index);
  }

  private short doGet(int index) {
    return JNISharedMemIfaceJNI.VectorUint8_doGet(swigCPtr, this, index);
  }

  private short doSet(int index, short val) {
    return JNISharedMemIfaceJNI.VectorUint8_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    JNISharedMemIfaceJNI.VectorUint8_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
