#!/bin/sh

sudo apt update -y -qq

# JDK fix
cat /etc/hosts # optionally check the content *before*
sudo hostname "$(hostname | cut -c1-63)"
sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
cat /etc/hosts # optionally check the content *after*
cd ..

# GHDL
sudo apt install -y libgnat-4.9 zlib1g-dev
wget https://github.com/tgingold/ghdl/releases/download/v0.34/ghdl-v0.34-mcode-ubuntu.tgz
mkdir ghdl
tar -xvzf ghdl-v0.34-mcode-ubuntu.tgz -C ghdl

# iverilog (debian package 9.7 contain bugs)
sudo apt install -y gperf readline-common bison flex
wget https://github.com/steveicarus/iverilog/archive/v10_0.tar.gz
tar -xvf v10_0.tar.gz
cd iverilog-10_0
autoconf
./configure
make -j$(nproc)
sudo make install
cd ..

# cocotb
sudo apt install -y git make gcc g++ swig python-dev
git clone https://github.com/potentialventures/cocotb
cd cocotb
git reset --hard a463cee498346cb26fc215ced25c088039490665
cd ..

# Force cocotb to compile VPI to avoid race condition when tests are start in parallel
cd SpinalHDL/tester/src/test/python/spinal/Dummy
make TOPLEVEL_LANG=verilog
make TOPLEVEL_LANG=vhdl
cd ../../../../../../..

# Verilator
sudo apt install -y git make autoconf g++ flex bison  # First time prerequisites
git clone http://git.veripool.org/git/verilator   # Only first time
unset VERILATOR_ROOT  # For bash
cd verilator
git pull        # Make sure we're up-to-date
git checkout verilator_3_916
autoconf        # Create ./configure script
./configure
make -j$(nproc)
sudo make install
cd ..

cd SpinalHDL
