VERILOG_SOURCES =  $(PWD)/dump.v $(PWD)/../../../../../TopLevel.v
TOPLEVEL=TopLevel
MODULE=main
include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim
