TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(SPINALROOT)/Apb3SpiSlaveCtrl.v

TOPLEVEL=Apb3SpiSlaveCtrl
MODULE=Apb3SpiSlaveCtrlTester

#RANDOM_SEED=1500899963 COCOTB_ANSI_OUTPUT=true

include ../../common/Makefile.sim
