COMMON_PATH:=${abspath ${dir ${lastword ${MAKEFILE_LIST}}}}

export PYTHONPATH:=$(COMMON_PATH)/../..
SPINALROOT=${COMMON_PATH}/../../../../../..

ifeq ($(TOPLEVEL_LANG),vhdl)
	SIM ?= ghdl
endif


include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim


#$(info *** Base path :  ${COMMON_PATH} )
