TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(SPINALROOT)/I2cIoMaster.v

TOPLEVEL=I2cIoMaster
MODULE=ioMasterTester

#RANDOM_SEED=1500899963 COCOTB_ANSI_OUTPUT=true

include ../../common/Makefile.sim
