name: Run scala tests on Verilator 5.

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:  
  run-test:
    uses: ./.github/workflows/sbt-tests.yml
    with:
      scala_version: '2.12.18'
      runner_os: 'Linux'
      github_sha: ${{ github.sha }}
      docker_image_version: 'v1.3.0'
