TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(SPINALROOT)/Apb3SpiMasterCtrl.v

TOPLEVEL=Apb3SpiMasterCtrl
MODULE=Apb3SpiMasterCtrlTester

#RANDOM_SEED=1500899963 COCOTB_ANSI_OUTPUT=true

include ../../common/Makefile.sim
